spring:
    profiles:
        active: local
    main:
      allow-circular-references: true
      
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mappers/*.xml
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/rgt
    username: root
    password: 1234
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    max-total: 10
    max-idle: 5      

oauth2:
  google:
    client-id: 282448345578-0f9qqqff2l8udat2qttkv42it0le5icv.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo